version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo_user
      MYSQL_PASSWORD: matomo_password
    volumes:
      - db_data:/var/lib/mysql

  matomo:
    image: matomo:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_NAME: matomo
      MATOMO_DATABASE_USER: matomo_user
      MATOMO_DATABASE_PASSWORD: matomo_password
      MATOMO_DATABASE_ADAPTER: pdo_mysql
    volumes:
      - matomo_data:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  matomo_data:
